### ISSUE TITLE
[BUG] Can't Open Window

### ISSUE THREAD

**Issue by Crowguard** [averrin/director#2] opened 2022-07-22 21:27 UTC
Clicking the button results in this error and fails to open the window.

TypeError: args[1] is undefined
[Detected 2 packages: director, lib-wrapper]
    getPreset Sequencer.js:144
    convertToCode Sequencer.js:144
    getCode SequencerTab.svelte:39
    unsubscribe SequencerTab.svelte:27
    subscribe index.mjs:50
    instance$4 SequencerTab.svelte:20
    init index.mjs:1891
    SequencerTab director.js:38520
    create_if_block_2 director.js:41134
    create_default_slot MainUI.svelte:99
    create_slot index.mjs:69
    create_else_block$3$1 index.js:1608
    create_fragment$4$1 index.js:1721
    init index.mjs:1906
    ApplicationShell index.js:2091
    create_fragment director.js:41485
    init index.mjs:1906
    MainUI director.js:41679
    loadSvelteConfig loadSvelteConfig.js:73
    _injectHTML SvelteApplication.js:448
    _render foundry.js:3085
    _render SvelteApplication.js:771
    render foundry.js:3021
    show MainApplication.js:108
    <anonymous> init.js:38
    _call foundry.js:294
    callAll foundry.js:253
    setupGame foundry.js:5567
    _initializeGameView foundry.js:6514
    _initializeView foundry.js:6490
    initialize foundry.js:5431
    call_wrapped libWrapper-wrapper.js:511
    libWrapperInit libWrapper-api.js:794
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:62701
    async* foundry.js:62683
foundry.js:319:30

Foundry 9.269
D&D 5e 1.6.3
Director 0.6.1

**Comment by averrin** [comment] 2022-07-23 09:47
Looks like it's a bug of TokenMagicFX integration. Do you have it installed? In the upcoming release it's fixed by design (new API for integrations), but now you can easily fix it by enabling the TokenMagic module. But if you want, I can make hotfix release.

**Comment by averrin** [comment] 2022-07-25 14:59
Released 0.7.0. Should be fixed

**Closed as completed** 2022-07-25 14:59 UTC
Labels: bug
